version: '2'
services:
    dingdingisv-app:
        image: dingdingisv
        external_links:
            - dingdingisv-mysql:mysql
            - dingdingisv-elasticsearch:elasticsearch
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/dingdingisv?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
    dingdingisv-mysql:
        extends:
            file: mysql.yml
            service: dingdingisv-mysql
    dingdingisv-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: dingdingisv-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
